---
before_script:
  - . /duneci/bin/duneci-init-job
  - duneci-install-module https://gitlab.dune-project.org/martin.nolte/dune-polygongrid


.dune28: &dune28
  script: duneci-standard-test
  before_script:
  - duneci-install-module https://gitlab.dune-project.org/extensions/dune-alugrid.git
  tags: [duneci]

dune:2.8-debian-10-gcc-8-17:
  <<: *dune28
  image: registry.dune-project.org/docker/ci/dune:2.8-debian-10-gcc-8-17

dune:2.8-ubuntu-18.04-clang-6-17:
 <<: *dune28
 image: registry.dune-project.org/docker/ci/dune:2.8-ubuntu-18.04-clang-6-17
