[build-system]
requires = ['setuptools', 'wheel', 'scikit-build', 'cmake', 'ninja', 'requests', 'dune-common<=2.8.0.dev', 'dune-geometry<=2.8.0.dev', 'dune-grid<=2.8.0.dev', 'dune-localfunctions<=2.8.0.dev']
build-backend = 'setuptools.build_meta'
