---

debian:11--gcc:
  image: registry.dune-project.org/docker/ci/debian:11
  tags:
    - "duneci"
  script:
    - mkdir build && cd build
    - cmake ..
    - make
    - ctest

debian:10--gcc:
  image: registry.dune-project.org/docker/ci/debian:10
  tags:
    - "duneci"
  script:
    - mkdir build && cd build
    - cmake ..
    - make
    - ctest

