################################
# Dune module information file #
################################

# Name of the module
Module: dune-ftworth
Version: 0.0
Maintainer: peter.bastian@iwr.uni-heidelberg.de
# Required build dependencies
Depends: dune-common dune-geometry dune-uggrid dune-grid dune-alugrid dune-istl dune-localfunctions dune-typetree dune-functions dune-pdelab
# Optional build dependencies
#Suggests:
